import Head from "next/head";
import Image from "next/image";
import clsx from "clsx";
import classes from "../styles/Home.module.css";
import { PlusCircleIcon } from "@heroicons/react/outline";

export default function Home() {
  return (
    <div>
      <Head>
        <title>TodoList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={clsx("bg-white h-20 mt-12 p-5  w-screen")}>
        <figure className={clsx("relative", classes.image)}>
          <Image src="/qinlogo.svg" layout="fill" objectFit="contain" />
        </figure>
      </header>

      <main className={clsx("mt-10 w-screen", classes.main)}>
        <div className={clsx("pl-24 w-96 mx-auto")}>
          <h1 className={clsx("mb-1", classes.font, classes.today)}>
            今日する
          </h1>
          <PlusCircleIcon className={clsx("inline pb-1 w-6 text-gray-500")} />
          <input
            className={clsx(
              "appearance-none border-2 border-white rounded-full py-2 px-4 ml-1 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500",
              classes.input
            )}
            id="inline-full-name"
            type="text"
            placeholder="タスクを追加する"
          />
          <h1 className={clsx("mt-8", classes.font, classes.tomorrow)}>
            明日する
          </h1>
          <PlusCircleIcon className={clsx("inline pb-1 w-6 text-gray-500")} />
          <input
            className={clsx(
              "appearance-none border-2 border-white rounded-full py-2 px-4 ml-1 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500",
              classes.input2
            )}
            id="inline-full-name"
            type="text"
            placeholder="タスクを追加する"
          />
          <h1 className={clsx("mt-8", classes.font, classes.next)}>今度する</h1>
          <PlusCircleIcon className={clsx("inline pb-1 w-6 text-gray-500")} />
          <input
            className={clsx(
              "appearance-none border-2 border-white rounded-full py-2 px-4 ml-1 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500",
              classes.input3
            )}
            id="inline-full-name"
            type="text"
            placeholder="タスクを追加する"
          />
        </div>
      </main>
    </div>
  );
}
